# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 776d1b1810079bbedbf28ae3fe5ebdb5aacef89b57502c704b4deae8e6236e14f131e569ca33cb739ad0bb8803b4cd90d825fc7bf779b9b1c6fa5c799caed3e2

test:
  secret_key_base: ae104ea2c25e727bd9158421e0a381494d1a460b7c7aea034c9c214f98a93e0bfa104d7d0b571ca86b407b20936626e66bf4d89287fcd2ff2817c1f88abc6927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
